// Metadata for the pillar demos (server-safe — no engine/browser code, so it can
// be imported by server components for the /demos index and per-demo pages). The
// engine factories live in components/pillar-demos/engines.ts (client-only).

export type PillarKey =
  | 'flow-field'
  | 'maze-search'
  | 'swarm-landscape'
  | 'boids'
  | 'procedural-dungeon'
  | 'game-of-life'

export type PillarMeta = {
  key: PillarKey
  pillar: string
  accent: string
  eyebrow: string
  title: string
  caption: string // short, for compact embeds
  blurb: string // longer, for the demo page + index card
  chips: string[]
  height: number // compact-embed height on home/research
  fullHeight: number // interactive height on the demo page
  how: string // "how it works" paragraph on the demo page
}

export const PILLAR_DEMOS: Record<PillarKey, PillarMeta> = {
  'flow-field': {
    key: 'flow-field',
    pillar: 'Generative & Agentic AI',
    accent: '#8b7bf0',
    eyebrow: 'Latent flow field · generative',
    title: 'A field that self-organizes',
    caption: 'A living particle field — connections form and dissolve as emergence, a stand-in for the generative process.',
    blurb:
      'Particles drift along a hidden sinusoidal flow, forming and dissolving connections as they pass — emergence as a stand-in for the generative process. On the full demo, move your cursor to perturb the field.',
    chips: ['Particle flow', 'Emergent structure', 'Cursor-reactive'],
    height: 200,
    fullHeight: 360,
    how: 'Each particle reads a fixed flow field — a direction it should drift, derived from a sine of its position — and steers along it while a light damping keeps motion smooth. Whenever two particles come within a short radius, a faint link is drawn between them, so structure appears and dissolves purely from local proximity. The pointer adds a repulsive push, letting you carve temporary voids in the field.',
  },
  'maze-search': {
    key: 'maze-search',
    pillar: 'Computational Intelligence & Optimization',
    accent: '#4d8df0',
    eyebrow: 'Breadth-first search · shortest path',
    title: 'A search solving a maze',
    caption: 'Breadth-first search floods a perfect maze from the start, then traces the shortest path to the exit.',
    blurb:
      'A perfect maze is carved, then breadth-first search floods outward from the start (teal) cell by cell until it reaches the exit (coral) — and traces the guaranteed shortest path back. The search restarts on a fresh maze each cycle.',
    chips: ['Maze generation', 'BFS flood', 'Shortest path'],
    height: 200,
    fullHeight: 344,
    how: 'The maze is generated by a randomized depth-first carve, guaranteeing exactly one path between any two cells. Breadth-first search then expands the frontier evenly in all directions, recording each cell’s parent as it goes; because BFS explores in order of distance, the first time it reaches the exit it has found the shortest route, which is then reconstructed by walking the parent pointers back to the start.',
  },
  'swarm-landscape': {
    key: 'swarm-landscape',
    pillar: 'Computational Intelligence & Optimization',
    accent: '#21b3a0',
    eyebrow: 'Swarm intelligence · fitness landscape',
    title: 'A swarm foraging a landscape',
    caption: 'Agents forage a multimodal landscape, combining local flocking with a pull toward the best-known peak.',
    blurb:
      'A flock of agents forages a multimodal fitness landscape — brighter regions are higher fitness. Local flocking rules combine with a particle-swarm pull toward each agent’s own best and the globally best-known peak, so the swarm converges on high ground without any agent seeing the whole map.',
    chips: ['Particle swarm', 'Fitness landscape', 'Global best'],
    height: 200,
    fullHeight: 360,
    how: 'Every agent remembers the best spot it has personally found and is told the best spot any agent has found. Its velocity blends three pulls — inertia, a tug toward its personal best, and a tug toward the global best — plus light flocking with nearby agents. Sampling the landscape as they move, agents update those bests continuously, so the whole swarm climbs toward the tallest peak while still exploring. Reset for a new random landscape.',
  },
  boids: {
    key: 'boids',
    pillar: 'Games Informatics & Engagement Modelling',
    accent: '#f2683f',
    eyebrow: 'Emergent flocking · agent-based',
    title: 'Emergence you can disturb',
    caption: 'Boids flocking from three local rules — alignment, cohesion, separation — with no leader.',
    blurb:
      'Flocking with no leader: each agent follows just three local rules — align with neighbours, steer toward their centre, and avoid crowding — and coherent flocks emerge on their own. On the full demo, sweep the cursor to scatter the flock and click to seed more agents.',
    chips: ['Alignment · cohesion · separation', 'Emergent flocks', 'Cursor-reactive'],
    height: 200,
    fullHeight: 360,
    how: 'There is no global plan. For each agent, the model averages the headings and positions of neighbours within a radius (alignment and cohesion) and adds a short-range push away from any that are too close (separation). Those three small forces, applied every frame, are enough for lifelike flocks to form, split, and merge. The cursor acts as a predator the agents flee, and clicking spawns a fresh cluster.',
  },
  'procedural-dungeon': {
    key: 'procedural-dungeon',
    pillar: 'Games Informatics & Engagement Modelling',
    accent: '#f2683f',
    eyebrow: 'Procedural dungeon · content generation',
    title: 'A level from nothing',
    caption: 'A roguelike level synthesized from nothing — rooms scattered, then stitched with corridors.',
    blurb:
      'A roguelike level built from nothing: non-overlapping rooms are scattered across the grid, then stitched together with L-shaped corridors so every room is reachable. Every roll is unique. On the full demo, click or hit Regenerate to roll a new one.',
    chips: ['Room scatter', 'Corridor stitching', 'Unique every roll'],
    height: 200,
    fullHeight: 344,
    how: 'The generator repeatedly proposes a randomly sized room at a random spot and keeps it only if it does not overlap any existing room, giving a sparse, non-uniform layout. It then connects consecutive rooms with L-shaped corridors carved between their centres, guaranteeing the whole level is traversable. Because every placement is random, no two levels are alike — the core idea behind procedural content generation.',
  },
  'game-of-life': {
    key: 'game-of-life',
    pillar: 'Games Informatics & Engagement Modelling',
    accent: '#84b53a',
    eyebrow: 'Emergence · cellular automata',
    title: 'A universe from four rules',
    caption: "Conway's Game of Life — gliders and oscillators nobody encoded, from four rules about neighbours.",
    blurb:
      "Conway's Game of Life: every cell lives, dies or is born according to four rules about how many neighbours it has, and that is the entire specification. Gliders, blinkers and still lifes appear anyway. On the full demo, click and drag the grid to paint your own seed.",
    chips: ['Four local rules', 'Toroidal grid', 'Paintable seed'],
    height: 200,
    fullHeight: 344,
    how: 'The board wraps at every edge, so the world has no boundary. Each generation, a live cell with two or three live neighbours survives, a live cell with any other count dies, and a dead cell with exactly three live neighbours is born — that is all four rules. Structure is never designed in: gliders that walk across the grid, oscillators that beat on a fixed period, and still lifes that never change all fall out of those rules alone, which is why Life is the standard illustration of emergence. A board that dies out reseeds itself.',
  },
}

export const PILLAR_ORDER: PillarKey[] = [
  'flow-field',
  'maze-search',
  'swarm-landscape',
  'boids',
  'procedural-dungeon',
  'game-of-life',
]
